### ISSUE TITLE
Add usage of @apply directive in styled JSX

### ISSUE THREAD

**Issue by tholander** [andybroger/nextjs-tailwindcss#1]
I can't figure out how to make tailwind's directives work in styled jsx.

For example
```javascript
export const Layout = () => (
  <>
    <section>
        <button className="custom-btn bg-red-500">Button 1</button>
        <button className="custom-btn bg-red-600">Button 2</button>
        <button className="custom-btn bg-red-700">Button 2</button>
    </section>
    <style jsx>{`
        .custom-btn {
            @apply text-white font-bold py-2 px-4 rounded;
        }
    `}</style>
  </>
);
```
I'd like this kind of code to work, but the `@apply` directive seems to not have been transformed

**Comment by andybroger** [comment]
i didn't check it by myself, but could you try it with following:

`npm install --save styled-jsx-plugin-postcss`

And add following to your .babelrc:

```json
{
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx": {
          "plugins": [
            "styled-jsx-plugin-postcss"
          ]
        }
      }
    ]
  ]
}
```

**Comment by andybroger** [comment]
@tholander check out the [jsx-tailwind branch](https://github.com/andybroger/nextjs-tailwindcss/tree/jsx-tailwind) this example is working with styled-jsx tags.

**Comment by tholander** [comment]
nice ! it works very fine
thank !

**Comment by andybroger** [comment]
> check out the [jsx-tailwind branch](https://github.com/andybroger/nextjs-tailwindcss/tree/jsx-tailwind) this example is working with styled-jsx tags. [b3e7bdb](https://github.com/andybroger/nextjs-tailwindcss/commit/b3e7bdbc776076789e3029b1383668940e5e46e8)
